### Signup new user
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "email": "c@c.io",
  "password": "test123"
}

### Signin user
POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "email": "d@d.io",
  "password": "test123"
}

### Sign out user
POST http://localhost:4000/auth/signout

### Get currently signed in user
GET http://localhost:4000/auth/whoami

### Get user by id
GET http://localhost:4000/auth/1

### Find all users with a given email
GET http://localhost:4000/auth?email=test@test.io

### Delete user by id
DELETE http://localhost:4000/auth/5

### Update a user by id
PATCH http://localhost:4000/auth/4
Content-Type: application/json

{
  "email": "test@test.io",
  "password": "test123"
}